export const SUBMIT_SIGN_UP_STARTED = 'SUBMIT_SIGN_UP_STARTED'
export const SUBMIT_SIGN_UP_SUCCESS = 'SUBMIT_SIGN_UP_SUCCESS'
export const SUBMIT_SIGN_UP_FAIL = 'SUBMIT_SIGN_UP_FAIL'

export const SUBMIT_LOG_IN_STARTED = 'SUBMIT_LOG_IN_STARTED'
export const SUBMIT_LOG_IN_SUCCESS = 'SUBMIT_LOG_IN_SUCCESS'
export const SUBMIT_LOG_IN_FAIL = 'SUBMIT_LOG_IN_FAIL'

export const WATCH_AUTH_STATUS_STARTED = 'WATCH_AUTH_STATUS_STARTED'
export const WATCH_AUTH_STATUS_AUTH = 'WATCH_AUTH_STATUS_AUTH'
export const WATCH_AUTH_STATUS_NOT_AUTH = 'WATCH_AUTH_STATUS_NOT_AUTH'

export const UPDATE_AUTH_DISPLAY_NAME_STARTED = 'UPDATE_AUTH_DISPLAY_NAME_STARTED'
export const UPDATE_AUTH_DISPLAY_NAME_SUCCESS = 'UPDATE_AUTH_DISPLAY_NAME_SUCCESS'
export const UPDATE_AUTH_DISPLAY_NAME_FAIL = 'UPDATE_AUTH_DISPLAY_NAME_FAIL'

export const SUBMIT_SIGN_OUT_STARTED = 'SUBMIT_SIGN_OUT_STARTED'
export const SUBMIT_SIGN_OUT_SUCCESS = 'SUBMIT_SIGN_OUT_SUCCESS'
export const SUBMIT_SIGN_OUT_FAIL = 'SUBMIT_SIGN_OUT_FAIL'

export const CREATE_USER_RECORD_STARTED = 'CREATE_USER_RECORD_STARTED'
export const CREATE_USER_RECORD_SUCCESS = 'CREATE_USER_RECORD_SUCCESS'
export const CREATE_USER_RECORD_FAIL = 'CREATE_USER_RECORD_FAIL'

export const ADD_ACCESS_TOKEN_STARTED = 'ADD_ACCESS_TOKEN_STARTED'
export const ADD_ACCESS_TOKEN_SUCCESS = 'ADD_ACCESS_TOKEN_SUCCESS'
export const ADD_ACCESS_TOKEN_FAIL = 'ADD_ACCESS_TOKEN_FAIL'

export const GET_USER_DATA_STARTED = 'GET_USER_DATA_STARTED'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL'

export const UPDATE_ACCOUNT_SETTINGS_STARTED = 'UPDATE_ACCOUNT_SETTINGS_STARTED'
export const UPDATE_ACCOUNT_SETTINGS_SUCCESS = 'UPDATE_ACCOUNT_SETTINGS_SUCCESS'
export const UPDATE_ACCOUNT_SETTINGS_FAIL = 'UPDATE_ACCOUNT_SETTINGS_FAIL'

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const GET_LIKES_STARTED = 'GET_LIKES_STARTED'
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS'
export const GET_LIKES_FAIL = 'GET_LIKES_FAIL'
